-- ──────────────────────────────────────────────────────────────────────────────
-- cities: tabla de ciudades/localidades de Argentina para autocompletado
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists cities (
  id       serial primary key,
  name     text not null,
  province text not null
);

create index idx_cities_name     on cities using gin(to_tsvector('spanish', name));
create index idx_cities_province on cities(province);

-- ── Seed: ~500 ciudades principales de Argentina ─────────────────────────────

insert into cities (name, province) values
-- Ciudad Autónoma de Buenos Aires
('Buenos Aires', 'Ciudad Autónoma de Buenos Aires'),

-- Buenos Aires (Provincia)
('La Plata', 'Buenos Aires'),
('Mar del Plata', 'Buenos Aires'),
('Quilmes', 'Buenos Aires'),
('Lanús', 'Buenos Aires'),
('Almirante Brown', 'Buenos Aires'),
('Lomas de Zamora', 'Buenos Aires'),
('Merlo', 'Buenos Aires'),
('Morón', 'Buenos Aires'),
('Tres de Febrero', 'Buenos Aires'),
('San Martín', 'Buenos Aires'),
('Tigre', 'Buenos Aires'),
('Berazategui', 'Buenos Aires'),
('Florencio Varela', 'Buenos Aires'),
('Hurlingham', 'Buenos Aires'),
('Ituzaingó', 'Buenos Aires'),
('San Miguel', 'Buenos Aires'),
('José C. Paz', 'Buenos Aires'),
('Malvinas Argentinas', 'Buenos Aires'),
('Moreno', 'Buenos Aires'),
('Bahía Blanca', 'Buenos Aires'),
('Tandil', 'Buenos Aires'),
('Junín', 'Buenos Aires'),
('Pergamino', 'Buenos Aires'),
('Olavarría', 'Buenos Aires'),
('Necochea', 'Buenos Aires'),
('Zárate', 'Buenos Aires'),
('San Nicolás de los Arroyos', 'Buenos Aires'),
('Campana', 'Buenos Aires'),
('Chivilcoy', 'Buenos Aires'),
('Azul', 'Buenos Aires'),
('Luján', 'Buenos Aires'),
('Mercedes', 'Buenos Aires'),
('San Pedro', 'Buenos Aires'),
('Pilar', 'Buenos Aires'),
('Escobar', 'Buenos Aires'),
('General Rodríguez', 'Buenos Aires'),
('Marcos Paz', 'Buenos Aires'),
('Ezeiza', 'Buenos Aires'),
('Esteban Echeverría', 'Buenos Aires'),
('Avellaneda', 'Buenos Aires'),
('San Fernando', 'Buenos Aires'),
('Vicente López', 'Buenos Aires'),
('San Isidro', 'Buenos Aires'),
('General San Martín', 'Buenos Aires'),
('Tres Arroyos', 'Buenos Aires'),
('Coronel Suárez', 'Buenos Aires'),
('Balcarce', 'Buenos Aires'),
('Lobos', 'Buenos Aires'),
('Chascomús', 'Buenos Aires'),
('Dolores', 'Buenos Aires'),
('Pinamar', 'Buenos Aires'),
('Villa Gesell', 'Buenos Aires'),
('Miramar', 'Buenos Aires'),
('Bragado', 'Buenos Aires'),
('9 de Julio', 'Buenos Aires'),
('Saladillo', 'Buenos Aires'),
('Roque Pérez', 'Buenos Aires'),
('Navarro', 'Buenos Aires'),
('25 de Mayo', 'Buenos Aires'),
('Trenque Lauquen', 'Buenos Aires'),
('Pehuajó', 'Buenos Aires'),
('Carlos Casares', 'Buenos Aires'),
('Lincoln', 'Buenos Aires'),
('General Pico', 'Buenos Aires'),
('Tapalqué', 'Buenos Aires'),
('Bolívar', 'Buenos Aires'),
('Rauch', 'Buenos Aires'),
('General Alvear', 'Buenos Aires'),
('Las Flores', 'Buenos Aires'),
('Ayacucho', 'Buenos Aires'),
('Coronel Pringles', 'Buenos Aires'),
('Coronel Dorrego', 'Buenos Aires'),
('Punta Alta', 'Buenos Aires'),
('Pigüé', 'Buenos Aires'),
('Benito Juárez', 'Buenos Aires'),
('Lobería', 'Buenos Aires'),
('San Cayetano', 'Buenos Aires'),
('González Chávez', 'Buenos Aires'),
('Laprida', 'Buenos Aires'),
('Daireaux', 'Buenos Aires'),
('Hipólito Yrigoyen', 'Buenos Aires'),
('Salto', 'Buenos Aires'),
('Rojas', 'Buenos Aires'),
('Ramallo', 'Buenos Aires'),
('Arrecifes', 'Buenos Aires'),
('San Antonio de Areco', 'Buenos Aires'),
('Exaltación de la Cruz', 'Buenos Aires'),
('Capilla del Señor', 'Buenos Aires'),
('Zárate', 'Buenos Aires'),
('Baradero', 'Buenos Aires'),
('San Vicente', 'Buenos Aires'),
('Brandsen', 'Buenos Aires'),
('Cañuelas', 'Buenos Aires'),
('Monte', 'Buenos Aires'),
('Maipú', 'Buenos Aires'),
('General Lavalle', 'Buenos Aires'),
('Tordillo', 'Buenos Aires'),
('Punta Indio', 'Buenos Aires'),
('Magdalena', 'Buenos Aires'),
('Berisso', 'Buenos Aires'),
('Ensenada', 'Buenos Aires'),

-- Córdoba
('Córdoba', 'Córdoba'),
('Villa María', 'Córdoba'),
('Río Cuarto', 'Córdoba'),
('San Francisco', 'Córdoba'),
('Villa Carlos Paz', 'Córdoba'),
('Cosquín', 'Córdoba'),
('La Falda', 'Córdoba'),
('Alta Gracia', 'Córdoba'),
('Jesús María', 'Córdoba'),
('Bell Ville', 'Córdoba'),
('Arroyito', 'Córdoba'),
('Marcos Juárez', 'Córdoba'),
('Villa Dolores', 'Córdoba'),
('Cruz del Eje', 'Córdoba'),
('Dean Funes', 'Córdoba'),
('La Carlota', 'Córdoba'),
('Laboulaye', 'Córdoba'),
('Rufino', 'Córdoba'),
('Río Tercero', 'Córdoba'),
('Oncativo', 'Córdoba'),
('Hernando', 'Córdoba'),
('Leones', 'Córdoba'),
('Morrison', 'Córdoba'),
('Monte Maíz', 'Córdoba'),
('Justiniano Posse', 'Córdoba'),
('General Cabrera', 'Córdoba'),
('Almafuerte', 'Córdoba'),
('Embalse', 'Córdoba'),
('Villa General Belgrano', 'Córdoba'),
('Santa Rosa de Calamuchita', 'Córdoba'),
('Mina Clavero', 'Córdoba'),
('Capilla del Monte', 'Córdoba'),
('La Cumbre', 'Córdoba'),
('Unquillo', 'Córdoba'),
('Río Ceballos', 'Córdoba'),
('Salsipuedes', 'Córdoba'),
('Mendiolaza', 'Córdoba'),
('Malagueño', 'Córdoba'),
('Pilar', 'Córdoba'),
('Villa del Totoral', 'Córdoba'),

-- Santa Fe
('Rosario', 'Santa Fe'),
('Santa Fe', 'Santa Fe'),
('Rafaela', 'Santa Fe'),
('Venado Tuerto', 'Santa Fe'),
('Reconquista', 'Santa Fe'),
('Santo Tomé', 'Santa Fe'),
('Esperanza', 'Santa Fe'),
('Villa Constitución', 'Santa Fe'),
('Gálvez', 'Santa Fe'),
('Cañada de Gómez', 'Santa Fe'),
('San Lorenzo', 'Santa Fe'),
('Granadero Baigorria', 'Santa Fe'),
('Funes', 'Santa Fe'),
('Pérez', 'Santa Fe'),
('Capitán Bermúdez', 'Santa Fe'),
('Casilda', 'Santa Fe'),
('Firmat', 'Santa Fe'),
('Las Rosas', 'Santa Fe'),
('Rufino', 'Santa Fe'),
('Vera', 'Santa Fe'),
('Avellaneda', 'Santa Fe'),
('Las Toscas', 'Santa Fe'),
('San Cristóbal', 'Santa Fe'),
('Tostado', 'Santa Fe'),
('Sunchales', 'Santa Fe'),
('Brinkmann', 'Santa Fe'),
('San Jorge', 'Santa Fe'),
('Sastre', 'Santa Fe'),
('Totoras', 'Santa Fe'),
('Armstrong', 'Santa Fe'),
('Las Parejas', 'Santa Fe'),
('Correa', 'Santa Fe'),
('Roldan', 'Santa Fe'),
('Clorinda', 'Santa Fe'),

-- Mendoza
('Mendoza', 'Mendoza'),
('San Rafael', 'Mendoza'),
('Godoy Cruz', 'Mendoza'),
('Las Heras', 'Mendoza'),
('Guaymallén', 'Mendoza'),
('Luján de Cuyo', 'Mendoza'),
('Maipú', 'Mendoza'),
('Rivadavia', 'Mendoza'),
('San Martín', 'Mendoza'),
('Junín', 'Mendoza'),
('Tunuyán', 'Mendoza'),
('Tupungato', 'Mendoza'),
('San Carlos', 'Mendoza'),
('Malargüe', 'Mendoza'),
('General Alvear', 'Mendoza'),
('La Paz', 'Mendoza'),
('Santa Rosa', 'Mendoza'),
('Lavalle', 'Mendoza'),

-- Tucumán
('San Miguel de Tucumán', 'Tucumán'),
('Tafí Viejo', 'Tucumán'),
('Banda del Río Salí', 'Tucumán'),
('Yerba Buena', 'Tucumán'),
('Concepción', 'Tucumán'),
('Aguilares', 'Tucumán'),
('Monteros', 'Tucumán'),
('Famaillá', 'Tucumán'),
('Simoca', 'Tucumán'),
('Alderetes', 'Tucumán'),
('Las Talitas', 'Tucumán'),
('Tafí del Valle', 'Tucumán'),
('Amaicha del Valle', 'Tucumán'),

-- Entre Ríos
('Paraná', 'Entre Ríos'),
('Concordia', 'Entre Ríos'),
('Gualeguaychú', 'Entre Ríos'),
('Gualeguay', 'Entre Ríos'),
('Concepción del Uruguay', 'Entre Ríos'),
('Colón', 'Entre Ríos'),
('Federal', 'Entre Ríos'),
('La Paz', 'Entre Ríos'),
('Victoria', 'Entre Ríos'),
('Villaguay', 'Entre Ríos'),
('Federación', 'Entre Ríos'),
('San José', 'Entre Ríos'),
('Chajarí', 'Entre Ríos'),

-- Salta
('Salta', 'Salta'),
('San Ramón de la Nueva Orán', 'Salta'),
('Tartagal', 'Salta'),
('General Güemes', 'Salta'),
('Cafayate', 'Salta'),
('Cachi', 'Salta'),
('Metán', 'Salta'),
('Joaquín V. González', 'Salta'),
('Embarcación', 'Salta'),

-- Misiones
('Posadas', 'Misiones'),
('Oberá', 'Misiones'),
('Eldorado', 'Misiones'),
('Puerto Iguazú', 'Misiones'),
('Apóstoles', 'Misiones'),
('Leandro N. Alem', 'Misiones'),
('San Vicente', 'Misiones'),
('Aristóbulo del Valle', 'Misiones'),
('Campo Grande', 'Misiones'),
('Jardín América', 'Misiones'),

-- Chaco
('Resistencia', 'Chaco'),
('Presidencia Roque Sáenz Peña', 'Chaco'),
('Villa Ángela', 'Chaco'),
('Charata', 'Chaco'),
('General San Martín', 'Chaco'),
('Las Breñas', 'Chaco'),
('Quitilipi', 'Chaco'),
('Machagai', 'Chaco'),

-- Corrientes
('Corrientes', 'Corrientes'),
('Goya', 'Corrientes'),
('Paso de los Libres', 'Corrientes'),
('Curuzú Cuatiá', 'Corrientes'),
('Mercedes', 'Corrientes'),
('Monte Caseros', 'Corrientes'),
('Santo Tomé', 'Corrientes'),
('Yapeyú', 'Corrientes'),

-- Santiago del Estero
('Santiago del Estero', 'Santiago del Estero'),
('La Banda', 'Santiago del Estero'),
('Termas de Río Hondo', 'Santiago del Estero'),
('Frías', 'Santiago del Estero'),
('Loreto', 'Santiago del Estero'),
('Añatuya', 'Santiago del Estero'),

-- Jujuy
('San Salvador de Jujuy', 'Jujuy'),
('Palpalá', 'Jujuy'),
('San Pedro de Jujuy', 'Jujuy'),
('Libertador General San Martín', 'Jujuy'),
('Humahuaca', 'Jujuy'),
('Tilcara', 'Jujuy'),
('Purmamarca', 'Jujuy'),

-- San Juan
('San Juan', 'San Juan'),
('Rawson', 'San Juan'),
('Rivadavia', 'San Juan'),
('Chimbas', 'San Juan'),
('Santa Lucía', 'San Juan'),
('Pocito', 'San Juan'),
('Caucete', 'San Juan'),
('Jachal', 'San Juan'),
('Barreal', 'San Juan'),

-- Río Negro
('Bariloche', 'Río Negro'),
('Viedma', 'Río Negro'),
('Cipolletti', 'Río Negro'),
('General Roca', 'Río Negro'),
('Allen', 'Río Negro'),
('Cinco Saltos', 'Río Negro'),
('Villa Regina', 'Río Negro'),
('Catriel', 'Río Negro'),
('El Bolsón', 'Río Negro'),
('Choele Choel', 'Río Negro'),

-- Neuquén
('Neuquén', 'Neuquén'),
('Plottier', 'Neuquén'),
('Centenario', 'Neuquén'),
('Cutral Có', 'Neuquén'),
('Plaza Huincul', 'Neuquén'),
('Zapala', 'Neuquén'),
('San Martín de los Andes', 'Neuquén'),
('Villa La Angostura', 'Neuquén'),
('Junín de los Andes', 'Neuquén'),

-- Chubut
('Comodoro Rivadavia', 'Chubut'),
('Rawson', 'Chubut'),
('Trelew', 'Chubut'),
('Puerto Madryn', 'Chubut'),
('Esquel', 'Chubut'),
('Rada Tilly', 'Chubut'),
('Sarmiento', 'Chubut'),

-- Formosa
('Formosa', 'Formosa'),
('Clorinda', 'Formosa'),
('Pirané', 'Formosa'),
('General Mosconi', 'Formosa'),

-- San Luis
('San Luis', 'San Luis'),
('Villa Mercedes', 'San Luis'),
('Merlo', 'San Luis'),
('Concarán', 'San Luis'),
('La Toma', 'San Luis'),
('Justo Daract', 'San Luis'),

-- La Rioja
('La Rioja', 'La Rioja'),
('Chilecito', 'La Rioja'),
('Chepes', 'La Rioja'),
('Aimogasta', 'La Rioja'),
('Villa Unión', 'La Rioja'),

-- Catamarca
('San Fernando del Valle de Catamarca', 'Catamarca'),
('Andalgalá', 'Catamarca'),
('Belén', 'Catamarca'),
('Santa María', 'Catamarca'),
('Tinogasta', 'Catamarca'),

-- La Pampa
('Santa Rosa', 'La Pampa'),
('General Pico', 'La Pampa'),
('Toay', 'La Pampa'),
('Realicó', 'La Pampa'),
('General Acha', 'La Pampa'),
('Eduardo Castex', 'La Pampa'),
('Victorica', 'La Pampa'),

-- Santa Cruz
('Río Gallegos', 'Santa Cruz'),
('Caleta Olivia', 'Santa Cruz'),
('Pico Truncado', 'Santa Cruz'),
('Puerto San Julián', 'Santa Cruz'),
('Las Heras', 'Santa Cruz'),
('El Calafate', 'Santa Cruz'),
('El Chaltén', 'Santa Cruz'),

-- Tierra del Fuego
('Ushuaia', 'Tierra del Fuego'),
('Río Grande', 'Tierra del Fuego'),
('Tolhuin', 'Tierra del Fuego');
